---
- name: installing nginx
  hosts: all
  become: true

  tasks:
    - name: install nginx
      state: latest
    - name: start nginx
      service:
        name: nginx
        state: started
